/** Chat-web email sign-in copy. Server refusals arrive already worded. */
export const EMAIL_COPY = {
  open: "Continue with email",
  signinTitle: "Sign in with email",
  signupTitle: "Create your account",
  signupHint:
    "We'll email a 6-digit code. Already use Google with this email? You keep the same account.",
  forgotTitle: "Reset your password",
  forgotHint:
    "We'll email a code to set a new password. This also adds a password to a Google account.",
  codeTitle: "Check your email",
  codeHint: (email: string) => `Enter the 6-digit code sent to ${email}.`,
  name: "Your name",
  email: "Email",
  password: "Password",
  newPassword: "New password",
  passwordRule: "Use 8 to 128 characters.",
  code: "6-digit code",
  signin: "Sign in",
  continue: "Continue",
  sendCode: "Send code",
  verify: "Verify and continue",
  savePassword: "Save password and sign in",
  forgot: "Forgot password?",
  createAccount: "Create account",
  haveAccount: "Have an account? Sign in",
  back: "Back",
  resend: "Resend code",
  resendIn: (s: number) => `Resend in ${s}s`,
  invalidEmail: "Enter a valid email address.",
  nameRequired: "Enter your name.",
  codeLength: "Enter the 6-digit code.",
  failed: "Something went wrong. Try again.",
  signedIn: "Signed in. Opening chat…",
} as const;
